package mskm.cleancode.application.validator;

public enum VALIDATION_ERROR {
    INSUFFICIENT_BALANCE,
    INVALID_PASSWORD,
    INVALID_CARD,
    ALREADY_EXISTS,
    NO_SUCH_ENTITY,
    NO_SUCH_CARD,
    NO_SUCH_USER,
    NO_SUCH_TRANSACTION,
    INVALID_AMOUNT,
}
