spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1:3306}/${DB_NAME:database}?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${PORT:8080}